name: ProjectWizard
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    macOS: "13.0"

targets:
  ProjectWizard:
    type: application
    platform: macOS
    sources:
      - src
      - path: resources
        type: folder
        buildPhase: resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.projectwizard
      INFOPLIST_FILE: resources/Info.plist
      SWIFT_VERSION: "5.9"
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Foundation.framework
