name: oflike-metal
options:
  bundleIdPrefix: com.oflike
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en

settings:
  MACOSX_DEPLOYMENT_TARGET: "13.0"
  SWIFT_VERSION: "5.9"
  CLANG_ENABLE_OBJC_ARC: YES
  CLANG_CXX_LANGUAGE_STANDARD: "c++17"
  CLANG_CXX_LIBRARY: "libc++"

targets:
  oflike-metal:
    type: application
    platform: macOS
    sources:
      - path: src
        excludes:
          - "**/.DS_Store"
      - path: shaders
        buildPhase: resources
      - path: resources
        buildPhase: resources
    settings:
      PRODUCT_NAME: oflike-metal
      PRODUCT_BUNDLE_IDENTIFIER: com.oflike.oflike-metal
      INFOPLIST_FILE: resources/Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      ENABLE_HARDENED_RUNTIME: YES
      COMBINE_HIDPI_IMAGES: YES
      SWIFT_OBJC_BRIDGING_HEADER: src/platform/bridge/oflike-metal-Bridging-Header.h
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/third_party/utf8
        - $(SRCROOT)/third_party/glm
        - $(SRCROOT)/third_party/tess2/Include
    dependencies:
      - target: tess2
    scheme:
      testTargets:
        - oflike-metalTests
      gatherCoverageData: true

  tess2:
    type: library.static
    platform: macOS
    sources:
      - path: third_party/tess2/Source
        includes:
          - "*.c"
          - "*.h"
      - path: third_party/tess2/Include
        includes:
          - "*.h"
        buildPhase: headers
    settings:
      PRODUCT_NAME: tess2
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/third_party/tess2/Include
        - $(SRCROOT)/third_party/tess2/Source

  oflike-metalTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - tests
    dependencies:
      - target: oflike-metal
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oflike.oflike-metalTests
