name: test_phase3
options:
  bundleIdPrefix: com.oflike.test_phase3
  deploymentTarget:
    macOS: "13.0"

targets:
  test_phase3:
    type: application
    platform: macOS
    sources:
      - src
      - ../../shaders/Basic2D.metal
      - ../../shaders/Basic3D.metal
      - ../../shaders/BlendModes.metal
      - path: resources
        type: folder
        buildPhase: resources
      # Note: Assets go in bin/data/ (openFrameworks style)
      # build_app.sh will copy bin/data to app bundle
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.oflike.test_phase3
      INFOPLIST_FILE: resources/Info.plist
      SWIFT_VERSION: "5.9"
      MTL_ENABLE_DEBUG_INFO: "NO"
      MTL_COMPILER_FLAGS: "-fmodules-cache-path=/tmp/oflike_metal_module_cache"
      SWIFT_OBJC_BRIDGING_HEADER: "$(PROJECT_DIR)/../../src/platform/bridge/oflike-metal-Bridging-Header.h"
      CLANG_CXX_LANGUAGE_STANDARD: "c++20"
      CLANG_CXX_LIBRARY: "libc++"
      ENABLE_HARDENED_RUNTIME: NO
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      HEADER_SEARCH_PATHS:
        - "$(PROJECT_DIR)/../../src"
      LIBRARY_SEARCH_PATHS:
        - "$(PROJECT_DIR)/../../build"
        - "$(PROJECT_DIR)/../../build/third_party"
      OTHER_LDFLAGS:
        - "-loflike-metal"
        - "-ltess2"
        - "-loscpack"
        - "-lpugixml"

    dependencies:
      - sdk: Cocoa.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreText.framework
      - sdk: ImageIO.framework
      - sdk: Accelerate.framework
      - sdk: AVFoundation.framework
      - sdk: CoreMedia.framework
      - sdk: CoreVideo.framework

    scheme:
      testTargets: []
